name: Spring Boot CI

on:
  push:
    branches: [main, sast]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java 

    - name: Build with Gradle
      run: gradle build

    - name: Run Tests
      run: gradle test

    - name: Run CodeQL analysis
      if: always()
      uses: github/codeql-action/analyze@v3

    - name: Run the Application
      run: |
        # nohup java -javaagent:"./raspdemo/rasp/rasp/rasp.jar" --add-opens java.base/jdk.internal.loader=ALL-UNNAMED -jar ./raspdemo/build/libs/raspdemo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        # echo "Application is running"
        gradle bootRun
